package com.kharagedition.tibetankeyboard

class EmojiItemList {


    companion object {
        private fun addEmojiItem(
            string: String,
            smileys: EmojiCategory,
            listOf: List<String>
        ): EmojiItem {
            return EmojiItem(string, smileys, listOf)
        }

        val allEmojis = mutableListOf(
            addEmojiItem("😀", EmojiCategory.SMILEYS, listOf("grinning", "smile", "happy", "face")),
            addEmojiItem("😃", EmojiCategory.SMILEYS, listOf("smile", "happy", "joy", "face")),
        addEmojiItem("😄", EmojiCategory.SMILEYS, listOf("big smile", "happy", "joy", "face")),
        addEmojiItem("😁", EmojiCategory.SMILEYS, listOf("grin", "happy", "teeth", "smile")),
        addEmojiItem("😅", EmojiCategory.SMILEYS, listOf("sweat", "relief", "nervous", "laugh")),
        addEmojiItem("😂", EmojiCategory.SMILEYS, listOf("laugh", "tears", "funny", "joy")),
        addEmojiItem("🤣", EmojiCategory.SMILEYS, listOf("rofl", "laugh", "funny", "joy")),
        addEmojiItem("😊", EmojiCategory.SMILEYS, listOf("smile", "happy", "blush", "friendly")),
        addEmojiItem("😇", EmojiCategory.SMILEYS, listOf("angel", "innocent", "happy", "smile")),
        addEmojiItem("🙂", EmojiCategory.SMILEYS, listOf("smile", "content", "friendly", "happy")),
        addEmojiItem("🙃", EmojiCategory.SMILEYS, listOf("upside down", "playful", "fun", "silly")),
        addEmojiItem("😉", EmojiCategory.SMILEYS, listOf("wink", "flirt", "playful", "fun")),
        addEmojiItem("😌", EmojiCategory.SMILEYS, listOf("relaxed", "calm", "peaceful", "happy")),
        addEmojiItem("😍", EmojiCategory.SMILEYS, listOf("love", "heart", "affection", "smile")),
        addEmojiItem("🥰", EmojiCategory.SMILEYS, listOf("love", "hearts", "affection", "cute")),
        addEmojiItem("😘", EmojiCategory.SMILEYS, listOf("kiss", "love", "heart", "affection")),
        addEmojiItem("😗", EmojiCategory.SMILEYS, listOf("kiss", "smile", "love", "affection")),
        addEmojiItem("😙", EmojiCategory.SMILEYS, listOf("kiss", "happy", "love", "affection")),
        addEmojiItem("😚", EmojiCategory.SMILEYS, listOf("kiss", "love", "affection", "happy")),
        addEmojiItem("😋", EmojiCategory.SMILEYS, listOf("yum", "delicious", "happy", "fun")),
        addEmojiItem("😛", EmojiCategory.SMILEYS, listOf("tongue", "playful", "fun", "silly")),
        addEmojiItem("😝", EmojiCategory.SMILEYS, listOf("tongue", "playful", "fun", "silly")),
        addEmojiItem("😜", EmojiCategory.SMILEYS, listOf("wink", "tongue", "fun", "silly")),
        addEmojiItem("🤪", EmojiCategory.SMILEYS, listOf("crazy", "fun", "silly", "weird")),
        addEmojiItem("🤨", EmojiCategory.SMILEYS, listOf("thinking", "skeptical", "curious", "confused")),
        addEmojiItem("🧐", EmojiCategory.SMILEYS, listOf("thinking", "curious", "investigate", "detective")),
        addEmojiItem("🤓", EmojiCategory.SMILEYS, listOf("nerd", "smart", "geek", "glasses")),
        addEmojiItem("😎", EmojiCategory.SMILEYS, listOf("cool", "sunglasses", "confident", "happy")),
        addEmojiItem("🤩", EmojiCategory.SMILEYS, listOf("starstruck", "love", "amazed", "happy")),
        addEmojiItem("🥳", EmojiCategory.SMILEYS, listOf("party", "celebrate", "happy", "fun")),
        addEmojiItem("😏", EmojiCategory.SMILEYS, listOf("smirk", "flirt", "confident", "sly")),
        addEmojiItem("😒", EmojiCategory.SMILEYS, listOf("unamused", "annoyed", "dislike", "meh")),
        addEmojiItem("😞", EmojiCategory.SMILEYS, listOf("sad", "disappointed", "unhappy", "down")),
        addEmojiItem("😔", EmojiCategory.SMILEYS, listOf("sad", "disappointed", "down", "unhappy")),
        addEmojiItem("😟", EmojiCategory.SMILEYS, listOf("worried", "concerned", "anxious", "sad")),
        addEmojiItem("😕", EmojiCategory.SMILEYS, listOf("confused", "uncertain", "puzzled", "unsure")),
        addEmojiItem("🙁", EmojiCategory.SMILEYS, listOf("sad", "unhappy", "frown", "down")),
        addEmojiItem("☹️", EmojiCategory.SMILEYS, listOf("frown", "sad", "unhappy", "disappointed")),
        addEmojiItem("😣", EmojiCategory.SMILEYS, listOf("persevere", "frustrated", "sad", "stress")),
        addEmojiItem("😖", EmojiCategory.SMILEYS, listOf("confounded", "frustrated", "annoyed", "sad")),
        addEmojiItem("😫", EmojiCategory.SMILEYS, listOf("tired", "weary", "exhausted", "sad")),
        addEmojiItem("😩", EmojiCategory.SMILEYS, listOf("weary", "tired", "frustrated", "sad")),
        addEmojiItem("🥺", EmojiCategory.SMILEYS, listOf("pleading", "puppy eyes", "sad", "cute")),
        addEmojiItem("😢", EmojiCategory.SMILEYS, listOf("cry", "sad", "tear", "upset")),
        addEmojiItem("😭", EmojiCategory.SMILEYS, listOf("sob", "cry", "sad", "tears")),
        addEmojiItem("😤", EmojiCategory.SMILEYS, listOf("triumph", "angry", "frustrated", "annoyed")),
        addEmojiItem("😠", EmojiCategory.SMILEYS, listOf("angry", "mad", "annoyed", "upset")),
        addEmojiItem("😡", EmojiCategory.SMILEYS, listOf("rage", "angry", "mad", "furious")),
        addEmojiItem("🤬", EmojiCategory.SMILEYS, listOf("swearing", "angry", "mad", "curse")),
        addEmojiItem("🤯", EmojiCategory.SMILEYS, listOf("mind blown", "shocked", "amazed", "surprised")),
        addEmojiItem("😳", EmojiCategory.SMILEYS, listOf("flushed", "embarrassed", "shy", "surprised")),
        addEmojiItem("🥵", EmojiCategory.SMILEYS, listOf("hot", "overheated", "sweaty", "heat")),
        addEmojiItem("🥶", EmojiCategory.SMILEYS, listOf("cold", "freezing", "chill", "ice")),
        addEmojiItem("😱", EmojiCategory.SMILEYS, listOf("scream", "fear", "shocked", "scared")),
        addEmojiItem("😨", EmojiCategory.SMILEYS, listOf("fear", "anxious", "nervous", "worried")),
        addEmojiItem("😰", EmojiCategory.SMILEYS, listOf("anxious", "sweat", "worried", "nervous")),
        addEmojiItem("😥", EmojiCategory.SMILEYS, listOf("sad", "disappointed", "sweat", "upset")),
        addEmojiItem("😓", EmojiCategory.SMILEYS, listOf("sweat", "tired", "stressed", "worried")),
        addEmojiItem("🤗", EmojiCategory.SMILEYS, listOf("hug", "friendly", "happy", "warm")), addEmojiItem("🤔", EmojiCategory.SMILEYS, listOf("thinking", "curious", "ponder", "question")), addEmojiItem("🤭", EmojiCategory.SMILEYS, listOf("shy", "oops", "embarrassed", "cover mouth")), addEmojiItem("🤫", EmojiCategory.SMILEYS, listOf("shh", "quiet", "secret", "silence")),
        addEmojiItem("🤥", EmojiCategory.SMILEYS, listOf("lying", "dishonest", "fib", "fake")),
        addEmojiItem("😶", EmojiCategory.SMILEYS, listOf("silent", "speechless", "meh", "neutral")),
        addEmojiItem("😐", EmojiCategory.SMILEYS, listOf("neutral", "meh", "expressionless", "face")),
        addEmojiItem("😑", EmojiCategory.SMILEYS, listOf("expressionless", "meh", "unimpressed", "face")),
        addEmojiItem("😬", EmojiCategory.SMILEYS, listOf("grimace", "awkward", "nervous", "face")),
        addEmojiItem("🙄", EmojiCategory.SMILEYS, listOf("roll eyes", "annoyed", "frustrated", "meh")),
        addEmojiItem("😯", EmojiCategory.SMILEYS, listOf("surprised", "wow", "shocked", "face")),
        addEmojiItem("😦", EmojiCategory.SMILEYS, listOf("frowning", "surprised", "sad", "worried")),
        addEmojiItem("😧", EmojiCategory.SMILEYS, listOf("anguished", "shocked", "worried", "sad")),
        addEmojiItem("😮", EmojiCategory.SMILEYS, listOf("open mouth", "surprised", "wow", "shocked")),
        addEmojiItem("😲", EmojiCategory.SMILEYS, listOf("astonished", "amazed", "shocked", "surprised")),
        addEmojiItem("🥱", EmojiCategory.SMILEYS, listOf("yawn", "tired", "sleepy", "bored")),
        addEmojiItem("😴", EmojiCategory.SMILEYS, listOf("sleep", "tired", "zzz", "rest")),
        addEmojiItem("🤤", EmojiCategory.SMILEYS, listOf("drool", "hungry", "yummy", "desire")),
        addEmojiItem("😪", EmojiCategory.SMILEYS, listOf("sleepy", "tired", "sad", "sick")),
        addEmojiItem("😵", EmojiCategory.SMILEYS, listOf("dizzy", "confused", "shock", "overwhelmed")),
        addEmojiItem("🤐", EmojiCategory.SMILEYS, listOf("zip mouth", "secret", "quiet", "silence")),
        addEmojiItem("🥴", EmojiCategory.SMILEYS, listOf("woozy", "drunk", "sick", "dizzy")),
        addEmojiItem("🤢", EmojiCategory.SMILEYS, listOf("nauseated", "sick", "vomit", "ill")),
        addEmojiItem("🤮", EmojiCategory.SMILEYS, listOf("vomit", "sick", "nausea", "disgust")),
        addEmojiItem("🤧", EmojiCategory.SMILEYS, listOf("sneeze", "allergy", "sick", "cold")),
        addEmojiItem("😷", EmojiCategory.SMILEYS, listOf("mask", "sick", "ill", "medical")),
        addEmojiItem("🤒", EmojiCategory.SMILEYS, listOf("sick", "fever", "ill", "temperature")),
        addEmojiItem("🤕", EmojiCategory.SMILEYS, listOf("injured", "hurt", "bandage", "pain")),
        addEmojiItem("🤑", EmojiCategory.SMILEYS, listOf("money", "rich", "wealth", "cash")),
        addEmojiItem("🤠", EmojiCategory.SMILEYS, listOf("cowboy", "hat", "fun", "happy")),
        addEmojiItem("😈", EmojiCategory.SMILEYS, listOf("devil", "mischief", "evil", "playful")),
        addEmojiItem("👿", EmojiCategory.SMILEYS, listOf("angry devil", "evil", "mischief", "mad")),
        addEmojiItem("👹", EmojiCategory.SMILEYS, listOf("ogre", "monster", "scary", "creepy")),
        addEmojiItem("👺", EmojiCategory.SMILEYS, listOf("goblin", "monster", "scary", "mischief")),
        addEmojiItem("🤡", EmojiCategory.SMILEYS, listOf("clown", "funny", "silly", "circus")),
        addEmojiItem("💩", EmojiCategory.SMILEYS, listOf("poop", "funny", "mess", "gross")),
        addEmojiItem("👻", EmojiCategory.SMILEYS, listOf("ghost", "spooky", "fun", "scary")),
        addEmojiItem("💀", EmojiCategory.SMILEYS, listOf("skull", "death", "danger", "spooky")),

// --- Hands & Gestures ---
        addEmojiItem("👋", EmojiCategory.SMILEYS, listOf("wave", "hello", "hi", "greeting")),
        addEmojiItem("🤚", EmojiCategory.SMILEYS, listOf("raise hand", "stop", "hello", "hi")),
        addEmojiItem("🖐️", EmojiCategory.SMILEYS, listOf("hand", "high five", "stop", "gesture")),
        addEmojiItem("✋", EmojiCategory.SMILEYS, listOf("stop", "hand", "high five", "gesture")),
        addEmojiItem("🖖", EmojiCategory.SMILEYS, listOf("vulcan salute", "hello", "greeting", "hand")),
        addEmojiItem("👌", EmojiCategory.SMILEYS, listOf("okay", "perfect", "good", "gesture")),
        addEmojiItem("🤌", EmojiCategory.SMILEYS, listOf("pinch", "Italian", "gesture", "small")),
        addEmojiItem("🤏", EmojiCategory.SMILEYS, listOf("tiny", "pinch", "small", "gesture")),
        addEmojiItem("✌️", EmojiCategory.SMILEYS, listOf("peace", "victory", "hand", "gesture")),
        addEmojiItem("🤞", EmojiCategory.SMILEYS, listOf("fingers crossed", "hope", "luck", "gesture")),
        addEmojiItem("🤟", EmojiCategory.SMILEYS, listOf("love you", "hand", "gesture", "rock")),
        addEmojiItem("🤘", EmojiCategory.SMILEYS, listOf("rock on", "hand", "gesture", "fun")),
        addEmojiItem("🤙", EmojiCategory.SMILEYS, listOf("call me", "hand", "gesture", "fun")),
        addEmojiItem("👈", EmojiCategory.SMILEYS, listOf("point left", "gesture", "direction", "hand")),
        addEmojiItem("👉", EmojiCategory.SMILEYS, listOf("point right", "gesture", "direction", "hand")),
        addEmojiItem("👆", EmojiCategory.SMILEYS, listOf("point up", "gesture", "direction", "hand")),
        addEmojiItem("👇", EmojiCategory.SMILEYS, listOf("point down", "gesture", "direction", "hand")),
        addEmojiItem("☝️", EmojiCategory.SMILEYS, listOf("point up", "gesture", "hand", "direction")),
        addEmojiItem("✊", EmojiCategory.SMILEYS, listOf("fist", "power", "strong", "gesture")),
        addEmojiItem("👊", EmojiCategory.SMILEYS, listOf("punch", "fist", "hit", "gesture")),
        addEmojiItem("🤛", EmojiCategory.SMILEYS, listOf("left punch", "fist", "gesture", "fight")),
        addEmojiItem("🤜", EmojiCategory.SMILEYS, listOf("right punch", "fist", "gesture", "fight")),
        addEmojiItem("👏", EmojiCategory.SMILEYS, listOf("clap", "applause", "hand", "gesture")),
        addEmojiItem("🙌", EmojiCategory.SMILEYS, listOf("raise hands", "celebrate", "happy", "gesture")),
        addEmojiItem("👐", EmojiCategory.SMILEYS, listOf("open hands", "gesture", "welcome", "hand")),
        addEmojiItem("🤲", EmojiCategory.SMILEYS, listOf("palms up", "gesture", "offer", "hand")),
        addEmojiItem("🤝", EmojiCategory.SMILEYS, listOf("handshake", "agreement", "deal", "greeting")),
        addEmojiItem("🙏", EmojiCategory.SMILEYS, listOf("pray", "thanks", "gesture", "respect")),
        addEmojiItem("✍️", EmojiCategory.SMILEYS, listOf("writing", "gesture", "hand", "write")),
        addEmojiItem("👃", EmojiCategory.SMILEYS, listOf("nose", "smell", "face", "scent")),
        addEmojiItem("👂", EmojiCategory.SMILEYS, listOf("ear", "listen", "hearing", "sound")),
        addEmojiItem("👀", EmojiCategory.SMILEYS, listOf("eyes", "look", "watch", "see")),
            addEmojiItem("🐶", EmojiCategory.ANIMALS, listOf("dog", "pet", "animal", "puppy", "cute")),
            addEmojiItem("🐱", EmojiCategory.ANIMALS, listOf("cat", "pet", "animal", "kitty", "cute")),
            addEmojiItem("🐭", EmojiCategory.ANIMALS, listOf("mouse", "animal", "cute", "small")),
            addEmojiItem("🐹", EmojiCategory.ANIMALS, listOf("hamster", "pet", "animal", "cute")),
            addEmojiItem("🐰", EmojiCategory.ANIMALS, listOf("rabbit", "bunny", "animal", "cute")),
            addEmojiItem("🦊", EmojiCategory.ANIMALS, listOf("fox", "animal", "wild", "cute")),
            addEmojiItem("🐻", EmojiCategory.ANIMALS, listOf("bear", "animal", "wild", "cute")),
            addEmojiItem("🐼", EmojiCategory.ANIMALS, listOf("panda", "animal", "cute", "wild")),
            addEmojiItem("🐨", EmojiCategory.ANIMALS, listOf("koala", "animal", "cute", "wild")),
            addEmojiItem("🐯", EmojiCategory.ANIMALS, listOf("tiger", "animal", "wild", "fierce")),
            addEmojiItem("🦁", EmojiCategory.ANIMALS, listOf("lion", "animal", "wild", "fierce")),
            addEmojiItem("🐮", EmojiCategory.ANIMALS, listOf("cow", "farm", "animal", "moo")),
            addEmojiItem("🐷", EmojiCategory.ANIMALS, listOf("pig", "farm", "animal", "cute")),
            addEmojiItem("🐽", EmojiCategory.ANIMALS, listOf("pig nose", "animal", "cute", "snout")),
            addEmojiItem("🐸", EmojiCategory.ANIMALS, listOf("frog", "animal", "wild", "cute")),
            addEmojiItem("🐵", EmojiCategory.ANIMALS, listOf("monkey", "animal", "cute", "playful")),
            addEmojiItem("🙈", EmojiCategory.ANIMALS, listOf("see no evil", "monkey", "playful", "funny")),
            addEmojiItem("🙉", EmojiCategory.ANIMALS, listOf("hear no evil", "monkey", "funny", "playful")),
            addEmojiItem("🙊", EmojiCategory.ANIMALS, listOf("speak no evil", "monkey", "funny", "playful")),
            addEmojiItem("🐒", EmojiCategory.ANIMALS, listOf("monkey", "animal", "cute", "playful")),
            addEmojiItem("🐔", EmojiCategory.ANIMALS, listOf("chicken", "animal", "farm", "bird")),
            addEmojiItem("🐧", EmojiCategory.ANIMALS, listOf("penguin", "animal", "bird", "cute")),
            addEmojiItem("🐦", EmojiCategory.ANIMALS, listOf("bird", "animal", "fly", "feather")),
            addEmojiItem("🐤", EmojiCategory.ANIMALS, listOf("baby chick", "bird", "cute", "small")),
            addEmojiItem("🐣", EmojiCategory.ANIMALS, listOf("hatching chick", "bird", "cute", "egg")),
            addEmojiItem("🐥", EmojiCategory.ANIMALS, listOf("chick", "bird", "cute", "small")),
            addEmojiItem("🦆", EmojiCategory.ANIMALS, listOf("duck", "bird", "animal", "quack")),
            addEmojiItem("🦅", EmojiCategory.ANIMALS, listOf("eagle", "bird", "wild", "fly")),
            addEmojiItem("🦉", EmojiCategory.ANIMALS, listOf("owl", "bird", "wild", "night")),
            addEmojiItem("🦇", EmojiCategory.ANIMALS, listOf("bat", "animal", "night", "wild")),
            addEmojiItem("🐺", EmojiCategory.ANIMALS, listOf("wolf", "animal", "wild", "fierce")),
            addEmojiItem("🐗", EmojiCategory.ANIMALS, listOf("boar", "animal", "wild", "fierce")),
            addEmojiItem("🐴", EmojiCategory.ANIMALS, listOf("horse", "animal", "farm", "cute")),
            addEmojiItem("🦄", EmojiCategory.ANIMALS, listOf("unicorn", "mythical", "cute", "magical")),
            addEmojiItem("🐝", EmojiCategory.ANIMALS, listOf("bee", "insect", "nature", "honey")),
            addEmojiItem("🐛", EmojiCategory.ANIMALS, listOf("caterpillar", "insect", "nature", "bug")),
            addEmojiItem("🦋", EmojiCategory.ANIMALS, listOf("butterfly", "insect", "nature", "beautiful")),
            addEmojiItem("🐌", EmojiCategory.ANIMALS, listOf("snail", "insect", "slow", "nature")),
            addEmojiItem("🐞", EmojiCategory.ANIMALS, listOf("ladybug", "insect", "cute", "nature")),
            addEmojiItem("🐜", EmojiCategory.ANIMALS, listOf("ant", "insect", "small", "nature")),
            addEmojiItem("🦟", EmojiCategory.ANIMALS, listOf("mosquito", "insect", "bug", "nature")),
            addEmojiItem("🦗", EmojiCategory.ANIMALS, listOf("cricket", "insect", "bug", "nature")),
            addEmojiItem("🕷️", EmojiCategory.ANIMALS, listOf("spider", "insect", "bug", "creepy")),
            addEmojiItem("🦂", EmojiCategory.ANIMALS, listOf("scorpion", "insect", "wild", "danger")),
            addEmojiItem("🐢", EmojiCategory.ANIMALS, listOf("turtle", "animal", "slow", "cute")),
            addEmojiItem("🐍", EmojiCategory.ANIMALS, listOf("snake", "animal", "wild", "danger")),
            addEmojiItem("🦎", EmojiCategory.ANIMALS, listOf("lizard", "animal", "wild", "reptile")),
            addEmojiItem("🦖", EmojiCategory.ANIMALS, listOf("t-rex", "dinosaur", "wild", "prehistoric")),
            addEmojiItem("🦕", EmojiCategory.ANIMALS, listOf("dinosaur", "sauropod", "wild", "prehistoric")),
// --- Animals & Nature (continued) ---
            addEmojiItem("🐙", EmojiCategory.ANIMALS, listOf("octopus", "sea", "animal", "aquatic")),
            addEmojiItem("🦑", EmojiCategory.ANIMALS, listOf("squid", "sea", "animal", "aquatic")),
            addEmojiItem("🦐", EmojiCategory.ANIMALS, listOf("shrimp", "sea", "animal", "aquatic")),
            addEmojiItem("🦞", EmojiCategory.ANIMALS, listOf("lobster", "sea", "animal", "aquatic")),
            addEmojiItem("🦀", EmojiCategory.ANIMALS, listOf("crab", "sea", "animal", "aquatic")),
            addEmojiItem("🐡", EmojiCategory.ANIMALS, listOf("blowfish", "sea", "animal", "aquatic")),
            addEmojiItem("🐠", EmojiCategory.ANIMALS, listOf("fish", "sea", "animal", "aquatic")),
            addEmojiItem("🐟", EmojiCategory.ANIMALS, listOf("fish", "sea", "animal", "aquatic")),
            addEmojiItem("🐬", EmojiCategory.ANIMALS, listOf("dolphin", "sea", "animal", "cute")),
            addEmojiItem("🐳", EmojiCategory.ANIMALS, listOf("whale", "sea", "animal", "aquatic")),
            addEmojiItem("🐋", EmojiCategory.ANIMALS, listOf("whale", "sea", "animal", "aquatic")),
            addEmojiItem("🦈", EmojiCategory.ANIMALS, listOf("shark", "sea", "animal", "danger")),
            addEmojiItem("🐊", EmojiCategory.ANIMALS, listOf("crocodile", "animal", "wild", "danger")),
            addEmojiItem("🐅", EmojiCategory.ANIMALS, listOf("tiger", "wild", "animal", "fierce")),
            addEmojiItem("🐆", EmojiCategory.ANIMALS, listOf("leopard", "wild", "animal", "fierce")),
            addEmojiItem("🦓", EmojiCategory.ANIMALS, listOf("zebra", "wild", "animal", "striped")),
            addEmojiItem("🦍", EmojiCategory.ANIMALS, listOf("gorilla", "wild", "animal", "strong")),
            addEmojiItem("🦧", EmojiCategory.ANIMALS, listOf("orangutan", "wild", "animal", "cute")),
            addEmojiItem("🐘", EmojiCategory.ANIMALS, listOf("elephant", "wild", "animal", "big")),
            addEmojiItem("🦛", EmojiCategory.ANIMALS, listOf("hippopotamus", "wild", "animal", "big")),
            addEmojiItem("🦏", EmojiCategory.ANIMALS, listOf("rhinoceros", "wild", "animal", "big")),
            addEmojiItem("🐪", EmojiCategory.ANIMALS, listOf("camel", "desert", "animal", "hump")),
            addEmojiItem("🐫", EmojiCategory.ANIMALS, listOf("two-hump camel", "desert", "animal", "hump")),
            addEmojiItem("🦒", EmojiCategory.ANIMALS, listOf("giraffe", "wild", "animal", "tall")),
            addEmojiItem("🦘", EmojiCategory.ANIMALS, listOf("kangaroo", "wild", "animal", "jump")),
            addEmojiItem("🐃", EmojiCategory.ANIMALS, listOf("buffalo", "animal", "farm", "wild")),
            addEmojiItem("🐂", EmojiCategory.ANIMALS, listOf("ox", "farm", "animal", "strong")),
            addEmojiItem("🐄", EmojiCategory.ANIMALS, listOf("cow", "farm", "animal", "moo")),
            addEmojiItem("🐎", EmojiCategory.ANIMALS, listOf("horse", "animal", "farm", "ride")),
            addEmojiItem("🐖", EmojiCategory.ANIMALS, listOf("pig", "farm", "animal", "cute")),
            addEmojiItem("🐏", EmojiCategory.ANIMALS, listOf("ram", "animal", "farm", "horn")),
            addEmojiItem("🌲", EmojiCategory.ANIMALS, listOf("tree", "nature", "forest", "plant")),
            addEmojiItem("🌳", EmojiCategory.ANIMALS, listOf("tree", "nature", "forest", "plant")),
            addEmojiItem("🌴", EmojiCategory.ANIMALS, listOf("palm", "tree", "nature", "tropical")),
            addEmojiItem("🌵", EmojiCategory.ANIMALS, listOf("cactus", "nature", "desert", "plant")),
            addEmojiItem("🌶️", EmojiCategory.ANIMALS, listOf("chili", "spicy", "food", "plant")),
            addEmojiItem("🍄", EmojiCategory.ANIMALS, listOf("mushroom", "plant", "nature", "food")),
            addEmojiItem("🌾", EmojiCategory.ANIMALS, listOf("rice", "plant", "farm", "nature")),
            addEmojiItem("💐", EmojiCategory.ANIMALS, listOf("flowers", "nature", "bunch", "plant")),
            addEmojiItem("🌷", EmojiCategory.ANIMALS, listOf("tulip", "flower", "nature", "plant")),
            addEmojiItem("🌹", EmojiCategory.ANIMALS, listOf("rose", "flower", "love", "nature")),
            addEmojiItem("🥀", EmojiCategory.ANIMALS, listOf("wilted", "flower", "nature", "sad")),
            addEmojiItem("🌺", EmojiCategory.ANIMALS, listOf("hibiscus", "flower", "nature", "plant")),
            addEmojiItem("🌸", EmojiCategory.ANIMALS, listOf("cherry blossom", "flower", "nature", "plant")),
            addEmojiItem("🌼", EmojiCategory.ANIMALS, listOf("blossom", "flower", "nature", "plant")),
            addEmojiItem("🌻", EmojiCategory.ANIMALS, listOf("sunflower", "flower", "nature", "plant")),
            addEmojiItem("🌞", EmojiCategory.ANIMALS, listOf("sun", "nature", "bright", "day")),

// --- Food & Drink ---
            addEmojiItem("🍎", EmojiCategory.FOOD, listOf("apple", "fruit", "food", "red", "healthy")),
            addEmojiItem("🍐", EmojiCategory.FOOD, listOf("pear", "fruit", "food", "green", "healthy")),
            addEmojiItem("🍊", EmojiCategory.FOOD, listOf("orange", "fruit", "food", "citrus")),
            addEmojiItem("🍋", EmojiCategory.FOOD, listOf("lemon", "fruit", "food", "yellow", "citrus")),
            addEmojiItem("🍌", EmojiCategory.FOOD, listOf("banana", "fruit", "food", "yellow", "sweet")),
            addEmojiItem("🍉", EmojiCategory.FOOD, listOf("watermelon", "fruit", "food", "sweet", "summer")),
            addEmojiItem("🍇", EmojiCategory.FOOD, listOf("grapes", "fruit", "food", "purple", "sweet")),
            addEmojiItem("🍓", EmojiCategory.FOOD, listOf("strawberry", "fruit", "food", "red", "sweet")),
            addEmojiItem("🫐", EmojiCategory.FOOD, listOf("blueberry", "fruit", "food", "sweet")),
            addEmojiItem("🍈", EmojiCategory.FOOD, listOf("melon", "fruit", "food", "sweet")),
            addEmojiItem("🍒", EmojiCategory.FOOD, listOf("cherries", "fruit", "food", "red", "sweet")),
            addEmojiItem("🍑", EmojiCategory.FOOD, listOf("peach", "fruit", "food", "sweet", "orange")),
            addEmojiItem("🥭", EmojiCategory.FOOD, listOf("mango", "fruit", "food", "sweet", "tropical")),
            addEmojiItem("🍍", EmojiCategory.FOOD, listOf("pineapple", "fruit", "food", "tropical", "sweet")),
            addEmojiItem("🥥", EmojiCategory.FOOD, listOf("coconut", "fruit", "food", "tropical")),
            addEmojiItem("🥝", EmojiCategory.FOOD, listOf("kiwi", "fruit", "food", "green", "sweet")),
            addEmojiItem("🍅", EmojiCategory.FOOD, listOf("tomato", "vegetable", "food", "red")),
            addEmojiItem("🍆", EmojiCategory.FOOD, listOf("eggplant", "vegetable", "food", "purple")),
            addEmojiItem("🥑", EmojiCategory.FOOD, listOf("avocado", "fruit", "food", "green", "healthy")),
            addEmojiItem("🥦", EmojiCategory.FOOD, listOf("broccoli", "vegetable", "food", "green", "healthy")),
            addEmojiItem("🥬", EmojiCategory.FOOD, listOf("lettuce", "vegetable", "food", "green")),
            addEmojiItem("🥒", EmojiCategory.FOOD, listOf("cucumber", "vegetable", "food", "green", "healthy")),
// --- Activities & Sports ---
            addEmojiItem("⚽", EmojiCategory.ACTIVITIES, listOf("soccer", "football", "sport", "game", "ball")),
            addEmojiItem("🏀", EmojiCategory.ACTIVITIES, listOf("basketball", "sport", "game", "ball")),
            addEmojiItem("🏈", EmojiCategory.ACTIVITIES, listOf("football", "sport", "game", "ball")),
            addEmojiItem("⚾", EmojiCategory.ACTIVITIES, listOf("baseball", "sport", "game", "ball")),
            addEmojiItem("🥎", EmojiCategory.ACTIVITIES, listOf("softball", "sport", "game", "ball")),
            addEmojiItem("🎾", EmojiCategory.ACTIVITIES, listOf("tennis", "sport", "game", "ball")),
            addEmojiItem("🏐", EmojiCategory.ACTIVITIES, listOf("volleyball", "sport", "game", "ball")),
            addEmojiItem("🏉", EmojiCategory.ACTIVITIES, listOf("rugby", "sport", "game", "ball")),
            addEmojiItem("🥏", EmojiCategory.ACTIVITIES, listOf("frisbee", "sport", "game", "outdoor")),
            addEmojiItem("🎱", EmojiCategory.ACTIVITIES, listOf("billiards", "pool", "game", "ball")),
            addEmojiItem("🪀", EmojiCategory.ACTIVITIES, listOf("yo-yo", "toy", "game", "fun")),
            addEmojiItem("🏓", EmojiCategory.ACTIVITIES, listOf("table tennis", "ping pong", "sport", "game")),
            addEmojiItem("🏸", EmojiCategory.ACTIVITIES, listOf("badminton", "sport", "game", "racket")),
            addEmojiItem("🏒", EmojiCategory.ACTIVITIES, listOf("ice hockey", "sport", "game", "stick")),
            addEmojiItem("🏑", EmojiCategory.ACTIVITIES, listOf("field hockey", "sport", "game", "stick")),
            addEmojiItem("🥍", EmojiCategory.ACTIVITIES, listOf("lacrosse", "sport", "game", "stick")),
            addEmojiItem("🏏", EmojiCategory.ACTIVITIES, listOf("cricket", "sport", "game", "ball")),
            addEmojiItem("🪃", EmojiCategory.ACTIVITIES, listOf("boomerang", "sport", "game", "throw")),
            addEmojiItem("🥅", EmojiCategory.ACTIVITIES, listOf("goal", "sport", "game", "net")),
            addEmojiItem("⛳", EmojiCategory.ACTIVITIES, listOf("golf", "sport", "game", "hole")),
            addEmojiItem("🪁", EmojiCategory.ACTIVITIES, listOf("kite", "sport", "outdoor", "fun")),
            addEmojiItem("🏹", EmojiCategory.ACTIVITIES, listOf("archery", "sport", "game", "bow")),
            addEmojiItem("🎣", EmojiCategory.ACTIVITIES, listOf("fishing", "sport", "outdoor", "fish")),
            addEmojiItem("🤿", EmojiCategory.ACTIVITIES, listOf("diving", "sport", "water", "snorkel")),
            addEmojiItem("🥊", EmojiCategory.ACTIVITIES, listOf("boxing", "sport", "fight", "gloves")),
            addEmojiItem("🥋", EmojiCategory.ACTIVITIES, listOf("martial arts", "sport", "karate", "fight")),
            addEmojiItem("🎽", EmojiCategory.ACTIVITIES, listOf("running", "sport", "jersey", "athlete")),
            addEmojiItem("🛹", EmojiCategory.ACTIVITIES, listOf("skateboard", "sport", "outdoor", "fun")),
            addEmojiItem("🛷", EmojiCategory.ACTIVITIES, listOf("sled", "winter", "sport", "fun")),
            addEmojiItem("⛸️", EmojiCategory.ACTIVITIES, listOf("ice skate", "winter", "sport", "fun")),
            addEmojiItem("🥌", EmojiCategory.ACTIVITIES, listOf("curling", "sport", "winter", "stone")),
            addEmojiItem("🎿", EmojiCategory.ACTIVITIES, listOf("ski", "sport", "winter", "fun")),
            addEmojiItem("⛷️", EmojiCategory.ACTIVITIES, listOf("skier", "sport", "winter", "fun")),
            addEmojiItem("🏂", EmojiCategory.ACTIVITIES, listOf("snowboard", "sport", "winter", "fun")),
            addEmojiItem("🪂", EmojiCategory.ACTIVITIES, listOf("parachute", "sport", "sky", "fun")),
            addEmojiItem("🏋️", EmojiCategory.ACTIVITIES, listOf("weightlifting", "sport", "gym", "strength")),
            addEmojiItem("🤼", EmojiCategory.ACTIVITIES, listOf("wrestling", "sport", "fight", "athlete")),
            addEmojiItem("🤸", EmojiCategory.ACTIVITIES, listOf("gymnastics", "sport", "acrobat", "fun")),
            addEmojiItem("⛹️", EmojiCategory.ACTIVITIES, listOf("basketball player", "sport", "game", "ball")),
            addEmojiItem("🤺", EmojiCategory.ACTIVITIES, listOf("fencer", "sport", "fight", "weapon")),
            addEmojiItem("🤾", EmojiCategory.ACTIVITIES, listOf("handball", "sport", "game", "ball")),
            addEmojiItem("🏌️", EmojiCategory.ACTIVITIES, listOf("golfer", "sport", "game", "hole")),
            addEmojiItem("🏇", EmojiCategory.ACTIVITIES, listOf("horse racing", "sport", "race", "animal")),
            addEmojiItem("🧘", EmojiCategory.ACTIVITIES, listOf("yoga", "exercise", "meditation", "calm")),
            addEmojiItem("🏄", EmojiCategory.ACTIVITIES, listOf("surfing", "sport", "water", "fun")),
            addEmojiItem("🏊", EmojiCategory.ACTIVITIES, listOf("swimming", "sport", "water", "fun")),
            addEmojiItem("🤽", EmojiCategory.ACTIVITIES, listOf("water polo", "sport", "water", "game")),
            addEmojiItem("🚣", EmojiCategory.ACTIVITIES, listOf("rowing", "sport", "water", "fun")),
            addEmojiItem("🧗", EmojiCategory.ACTIVITIES, listOf("climbing", "sport", "outdoor", "adventure")),
            addEmojiItem("🚵", EmojiCategory.ACTIVITIES, listOf("mountain biking", "sport", "outdoor", "fun")),
            addEmojiItem("🚴", EmojiCategory.ACTIVITIES, listOf("cycling", "sport", "outdoor", "bike")),
            addEmojiItem("🏆", EmojiCategory.ACTIVITIES, listOf("trophy", "win", "award", "prize")),
            addEmojiItem("🥇", EmojiCategory.ACTIVITIES, listOf("gold medal", "win", "award", "prize")),
            addEmojiItem("🥈", EmojiCategory.ACTIVITIES, listOf("silver medal", "win", "award", "prize")),
            addEmojiItem("🥉", EmojiCategory.ACTIVITIES, listOf("bronze medal", "win", "award", "prize")),
            addEmojiItem("🏅", EmojiCategory.ACTIVITIES, listOf("medal", "award", "win", "prize")),
            addEmojiItem("🎖️", EmojiCategory.ACTIVITIES, listOf("military medal", "award", "win", "prize")),
            addEmojiItem("🏵️", EmojiCategory.ACTIVITIES, listOf("rosette", "award", "prize", "decoration")),
            addEmojiItem("🎗️", EmojiCategory.ACTIVITIES, listOf("ribbon", "award", "support", "charity")),
            addEmojiItem("🎫", EmojiCategory.ACTIVITIES, listOf("ticket", "event", "show", "game")),
            addEmojiItem("🎟️", EmojiCategory.ACTIVITIES, listOf("admission ticket", "event", "show", "game")),
            addEmojiItem("🎪", EmojiCategory.ACTIVITIES, listOf("circus", "show", "entertainment", "fun")),
            addEmojiItem("🤹", EmojiCategory.ACTIVITIES, listOf("juggling", "entertainment", "fun", "circus")),
            addEmojiItem("🎭", EmojiCategory.ACTIVITIES, listOf("theater", "play", "show", "mask")),
            addEmojiItem("🩰", EmojiCategory.ACTIVITIES, listOf("ballet", "dance", "show", "performance")),
            addEmojiItem("🎨", EmojiCategory.ACTIVITIES, listOf("painting", "art", "creative", "fun")),
            addEmojiItem("🎬", EmojiCategory.ACTIVITIES, listOf("movie", "film", "show", "entertainment")),
            addEmojiItem("🎤", EmojiCategory.ACTIVITIES, listOf("microphone", "sing", "music", "performance")),
            addEmojiItem("🎧", EmojiCategory.ACTIVITIES, listOf("headphones", "music", "audio", "listen")),
            addEmojiItem("🎼", EmojiCategory.ACTIVITIES, listOf("sheet music", "music", "note", "sound")),
            addEmojiItem("🎵", EmojiCategory.ACTIVITIES, listOf("musical note", "music", "sound", "tune")),
            addEmojiItem("🎶", EmojiCategory.ACTIVITIES, listOf("musical notes", "music", "sound", "tune")),
            addEmojiItem("🥁", EmojiCategory.ACTIVITIES, listOf("drum", "music", "instrument", "beat")),
            addEmojiItem("🪘", EmojiCategory.ACTIVITIES, listOf("djembe", "music", "instrument", "beat")),
            addEmojiItem("🎹", EmojiCategory.ACTIVITIES, listOf("piano", "music", "instrument", "keyboard")),
            addEmojiItem("🎷", EmojiCategory.ACTIVITIES, listOf("saxophone", "music", "instrument", "jazz")),
            addEmojiItem("🎺", EmojiCategory.ACTIVITIES, listOf("trumpet", "music", "instrument", "brass")),
            addEmojiItem("🪗", EmojiCategory.ACTIVITIES, listOf("accordion", "music", "instrument", "folk")),
            addEmojiItem("🎸", EmojiCategory.ACTIVITIES, listOf("guitar", "music", "instrument", "rock")),
            addEmojiItem("🪕", EmojiCategory.ACTIVITIES, listOf("banjo", "music", "instrument", "folk")),

// --- Travel & Places ---
            addEmojiItem("🚗", EmojiCategory.TRAVEL, listOf("car", "vehicle", "drive", "transport")),
            addEmojiItem("🚕", EmojiCategory.TRAVEL, listOf("taxi", "vehicle", "drive", "transport")),
            addEmojiItem("🚙", EmojiCategory.TRAVEL, listOf("suv", "vehicle", "drive", "transport")),
            addEmojiItem("🚌", EmojiCategory.TRAVEL, listOf("bus", "vehicle", "transport", "public")),
            addEmojiItem("🚎", EmojiCategory.TRAVEL, listOf("trolleybus", "vehicle", "transport", "public")),
            addEmojiItem("🏎️", EmojiCategory.TRAVEL, listOf("race car", "vehicle", "speed", "sport")),
            addEmojiItem("🚓", EmojiCategory.TRAVEL, listOf("police car", "vehicle", "emergency", "law")),
            addEmojiItem("🚑", EmojiCategory.TRAVEL, listOf("ambulance", "vehicle", "emergency", "health")),
            addEmojiItem("🚒", EmojiCategory.TRAVEL, listOf("fire truck", "vehicle", "emergency", "fire")),
            addEmojiItem("🚐", EmojiCategory.TRAVEL, listOf("van", "vehicle", "transport", "travel")),
            addEmojiItem("🛻", EmojiCategory.TRAVEL, listOf("pickup truck", "vehicle", "transport", "drive")),
            addEmojiItem("🚚", EmojiCategory.TRAVEL, listOf("truck", "vehicle", "transport", "delivery")),
            addEmojiItem("🚛", EmojiCategory.TRAVEL, listOf("lorry", "vehicle", "transport", "delivery")),
            addEmojiItem("🚜", EmojiCategory.TRAVEL, listOf("tractor", "vehicle", "farm", "agriculture")),
            addEmojiItem("🏍️", EmojiCategory.TRAVEL, listOf("motorcycle", "vehicle", "ride", "bike")),
            addEmojiItem("🛵", EmojiCategory.TRAVEL, listOf("scooter", "vehicle", "ride", "bike")),
            addEmojiItem("🚲", EmojiCategory.TRAVEL, listOf("bicycle", "vehicle", "ride", "bike")),
            addEmojiItem("🛴", EmojiCategory.TRAVEL, listOf("scooter", "vehicle", "ride", "fun")),
            addEmojiItem("🛺", EmojiCategory.TRAVEL, listOf("auto rickshaw", "vehicle", "transport", "ride")),
            addEmojiItem("🚨", EmojiCategory.TRAVEL, listOf("emergency light", "vehicle", "alarm", "warning")),
            addEmojiItem("🚔", EmojiCategory.TRAVEL, listOf("police car", "vehicle", "emergency", "law")),
            addEmojiItem("🚍", EmojiCategory.TRAVEL, listOf("bus", "vehicle", "transport", "public")),
            addEmojiItem("🚘", EmojiCategory.TRAVEL, listOf("oncoming car", "vehicle", "drive", "transport")),
            addEmojiItem("🚖", EmojiCategory.TRAVEL, listOf("oncoming taxi", "vehicle", "drive", "transport")),
// --- Travel & Places (continued) ---
            addEmojiItem("🚡", EmojiCategory.TRAVEL, listOf("aerial tramway", "cable car", "transport", "mountain")),
            addEmojiItem("🚠", EmojiCategory.TRAVEL, listOf("mountain cableway", "transport", "mountain", "ride")),
            addEmojiItem("🚟", EmojiCategory.TRAVEL, listOf("suspension railway", "transport", "ride", "mountain")),
            addEmojiItem("🚃", EmojiCategory.TRAVEL, listOf("railway car", "train", "transport", "public")),
            addEmojiItem("🚋", EmojiCategory.TRAVEL, listOf("tram car", "transport", "public", "ride")),
            addEmojiItem("🚞", EmojiCategory.TRAVEL, listOf("mountain railway", "train", "transport", "ride")),
            addEmojiItem("🚝", EmojiCategory.TRAVEL, listOf("monorail", "train", "transport", "ride")),
            addEmojiItem("🚄", EmojiCategory.TRAVEL, listOf("high-speed train", "train", "transport", "speed")),
            addEmojiItem("🚅", EmojiCategory.TRAVEL, listOf("bullet train", "train", "transport", "speed")),
            addEmojiItem("🚈", EmojiCategory.TRAVEL, listOf("light rail", "train", "transport", "public")),
            addEmojiItem("🚂", EmojiCategory.TRAVEL, listOf("steam locomotive", "train", "transport", "ride")),
            addEmojiItem("🚆", EmojiCategory.TRAVEL, listOf("train", "transport", "ride", "public")),
            addEmojiItem("🚇", EmojiCategory.TRAVEL, listOf("metro", "subway", "transport", "public")),
            addEmojiItem("🚊", EmojiCategory.TRAVEL, listOf("tram", "transport", "public", "ride")),
            addEmojiItem("🚉", EmojiCategory.TRAVEL, listOf("station", "train", "transport", "public")),
            addEmojiItem("✈️", EmojiCategory.TRAVEL, listOf("airplane", "flight", "travel", "plane")),
            addEmojiItem("🛫", EmojiCategory.TRAVEL, listOf("departure", "airplane", "flight", "travel")),
            addEmojiItem("🛬", EmojiCategory.TRAVEL, listOf("arrival", "airplane", "flight", "travel")),
            addEmojiItem("🛩️", EmojiCategory.TRAVEL, listOf("small airplane", "flight", "travel", "plane")),
            addEmojiItem("💺", EmojiCategory.TRAVEL, listOf("seat", "airplane", "chair", "travel")),
            addEmojiItem("🛰️", EmojiCategory.TRAVEL, listOf("satellite", "space", "travel", "communication")),
            addEmojiItem("🚀", EmojiCategory.TRAVEL, listOf("rocket", "space", "launch", "travel")),
            addEmojiItem("🛸", EmojiCategory.TRAVEL, listOf("ufo", "alien", "space", "flying")),
            addEmojiItem("🚁", EmojiCategory.TRAVEL, listOf("helicopter", "air", "flight", "travel")),
            addEmojiItem("🛶", EmojiCategory.TRAVEL, listOf("canoe", "boat", "water", "paddle")),
            addEmojiItem("⛵", EmojiCategory.TRAVEL, listOf("sailboat", "boat", "water", "travel")),
            addEmojiItem("🚤", EmojiCategory.TRAVEL, listOf("speedboat", "boat", "water", "travel")),
            addEmojiItem("🛥️", EmojiCategory.TRAVEL, listOf("motorboat", "boat", "water", "travel")),
            addEmojiItem("🛳️", EmojiCategory.TRAVEL, listOf("passenger ship", "boat", "water", "travel")),
            addEmojiItem("⛴️", EmojiCategory.TRAVEL, listOf("ferry", "boat", "water", "travel")),
            addEmojiItem("🚢", EmojiCategory.TRAVEL, listOf("ship", "boat", "water", "travel")),
            addEmojiItem("⚓", EmojiCategory.TRAVEL, listOf("anchor", "boat", "sail", "marine")),
            addEmojiItem("🪝", EmojiCategory.TRAVEL, listOf("hook", "ship", "fishing", "tool")),
            addEmojiItem("⛽", EmojiCategory.TRAVEL, listOf("fuel", "gas station", "transport", "vehicle")),
            addEmojiItem("🚧", EmojiCategory.TRAVEL, listOf("construction", "road", "traffic", "warning")),
            addEmojiItem("🚦", EmojiCategory.TRAVEL, listOf("traffic light", "road", "signal", "vehicle")),
            addEmojiItem("🚥", EmojiCategory.TRAVEL, listOf("traffic light", "road", "signal", "vehicle")),
            addEmojiItem("🗺️", EmojiCategory.TRAVEL, listOf("map", "travel", "navigation", "direction")),
            addEmojiItem("🗿", EmojiCategory.TRAVEL, listOf("moai", "statue", "monument", "historic")),
            addEmojiItem("🗽", EmojiCategory.TRAVEL, listOf("statue of liberty", "monument", "travel", "historic")),
            addEmojiItem("🏰", EmojiCategory.TRAVEL, listOf("castle", "building", "historic", "travel")),
            addEmojiItem("🏯", EmojiCategory.TRAVEL, listOf("japanese castle", "building", "historic", "travel")),
            addEmojiItem("🏟️", EmojiCategory.TRAVEL, listOf("stadium", "building", "sports", "event")),
            addEmojiItem("🎡", EmojiCategory.TRAVEL, listOf("ferris wheel", "amusement", "fun", "ride")),
            addEmojiItem("🎢", EmojiCategory.TRAVEL, listOf("roller coaster", "amusement", "fun", "ride")),
            addEmojiItem("🎠", EmojiCategory.TRAVEL, listOf("carousel", "amusement", "fun", "ride")),
            addEmojiItem("⛲", EmojiCategory.TRAVEL, listOf("fountain", "water", "park", "building")),
            addEmojiItem("⛱️", EmojiCategory.TRAVEL, listOf("umbrella", "beach", "sun", "vacation")),
            addEmojiItem("🏖️", EmojiCategory.TRAVEL, listOf("beach", "sand", "vacation", "sun")),
            addEmojiItem("🏝️", EmojiCategory.TRAVEL, listOf("desert island", "beach", "vacation", "tropical")),
            addEmojiItem("🏜️", EmojiCategory.TRAVEL, listOf("desert", "sand", "hot", "sun")),
            addEmojiItem("🌋", EmojiCategory.TRAVEL, listOf("volcano", "mountain", "lava", "nature")),
            addEmojiItem("⛰️", EmojiCategory.TRAVEL, listOf("mountain", "nature", "hike", "climb")),
            addEmojiItem("🏔️", EmojiCategory.TRAVEL, listOf("snow mountain", "nature", "hike", "climb")),
            addEmojiItem("🗻", EmojiCategory.TRAVEL, listOf("mount fuji", "mountain", "nature", "climb")),
            addEmojiItem("🏕️", EmojiCategory.TRAVEL, listOf("camping", "tent", "nature", "outdoor")),

// --- Objects & Symbols ---
            addEmojiItem("⌚", EmojiCategory.OBJECTS, listOf("watch", "time", "clock", "accessory")),
            addEmojiItem("📱", EmojiCategory.OBJECTS, listOf("smartphone", "phone", "mobile", "device")),
            addEmojiItem("📲", EmojiCategory.OBJECTS, listOf("phone with arrow", "call", "mobile", "message")),
            addEmojiItem("💻", EmojiCategory.OBJECTS, listOf("laptop", "computer", "device", "work")),
            addEmojiItem("⌨️", EmojiCategory.OBJECTS, listOf("keyboard", "computer", "type", "device")),
            addEmojiItem("🖥️", EmojiCategory.OBJECTS, listOf("desktop", "computer", "screen", "device")),
            addEmojiItem("🖨️", EmojiCategory.OBJECTS, listOf("printer", "office", "device", "work")),
            addEmojiItem("🖱️", EmojiCategory.OBJECTS, listOf("mouse", "computer", "device", "click")),
            addEmojiItem("🖲️", EmojiCategory.OBJECTS, listOf("trackball", "computer", "device", "click")),
            addEmojiItem("🕹️", EmojiCategory.OBJECTS, listOf("joystick", "game", "device", "play")),
            addEmojiItem("🗜️", EmojiCategory.OBJECTS, listOf("clamp", "tool", "mechanic", "object")),
            addEmojiItem("💽", EmojiCategory.OBJECTS, listOf("cd", "disk", "media", "storage")),
            addEmojiItem("💾", EmojiCategory.OBJECTS, listOf("floppy disk", "save", "storage", "data")),
            addEmojiItem("💿", EmojiCategory.OBJECTS, listOf("cd", "disk", "music", "storage")),
            addEmojiItem("📀", EmojiCategory.OBJECTS, listOf("dvd", "disk", "media", "storage")),
            addEmojiItem("📼", EmojiCategory.OBJECTS, listOf("videotape", "media", "storage", "video")),
            addEmojiItem("📷", EmojiCategory.OBJECTS, listOf("camera", "photo", "picture", "device")),
            addEmojiItem("📸", EmojiCategory.OBJECTS, listOf("camera with flash", "photo", "picture", "device")),
            addEmojiItem("📹", EmojiCategory.OBJECTS, listOf("video camera", "record", "device", "video")),
            addEmojiItem("🎥", EmojiCategory.OBJECTS, listOf("movie camera", "film", "record", "video")),
            addEmojiItem("📽️", EmojiCategory.OBJECTS, listOf("film projector", "movie", "video", "device")),
            addEmojiItem("🎞️", EmojiCategory.OBJECTS, listOf("film frames", "movie", "video", "media")),
            addEmojiItem("📞", EmojiCategory.OBJECTS, listOf("telephone receiver", "call", "phone", "talk")),
            addEmojiItem("☎️", EmojiCategory.OBJECTS, listOf("telephone", "call", "phone", "talk")),
            addEmojiItem("📟", EmojiCategory.OBJECTS, listOf("pager", "message", "device", "alert")),
            addEmojiItem("📠", EmojiCategory.OBJECTS, listOf("fax machine", "document", "office", "device")),
            addEmojiItem("📺", EmojiCategory.OBJECTS, listOf("television", "tv", "screen", "media")),
            addEmojiItem("📻", EmojiCategory.OBJECTS, listOf("radio", "audio", "music", "device")),
            addEmojiItem("🎙️", EmojiCategory.OBJECTS, listOf("microphone", "audio", "record", "sing")),
            addEmojiItem("🎚️", EmojiCategory.OBJECTS, listOf("level slider", "audio", "music", "control")),
            addEmojiItem("🎛️", EmojiCategory.OBJECTS, listOf("control knobs", "audio", "music", "device")),
            addEmojiItem("🧭", EmojiCategory.OBJECTS, listOf("compass", "navigation", "direction", "travel")),
            addEmojiItem("⏱️", EmojiCategory.OBJECTS, listOf("stopwatch", "time", "clock", "measure")),
            addEmojiItem("⏲️", EmojiCategory.OBJECTS, listOf("timer clock", "time", "measure", "countdown")),
            addEmojiItem("⏰", EmojiCategory.OBJECTS, listOf("alarm clock", "time", "wake", "sleep")),
            addEmojiItem("🕰️", EmojiCategory.OBJECTS, listOf("mantelpiece clock", "time", "clock", "measure")),
            addEmojiItem("⌛", EmojiCategory.OBJECTS, listOf("hourglass", "time", "wait", "measure")),
            addEmojiItem("⏳", EmojiCategory.OBJECTS, listOf("hourglass flowing", "time", "wait", "measure")),
            addEmojiItem("📡", EmojiCategory.OBJECTS, listOf("satellite antenna", "communication", "signal", "device")),
            addEmojiItem("🔋", EmojiCategory.OBJECTS, listOf("battery", "power", "charge", "device")),
            addEmojiItem("🔌", EmojiCategory.OBJECTS, listOf("electric plug", "power", "device", "charge")),
            addEmojiItem("💡", EmojiCategory.OBJECTS, listOf("light bulb", "idea", "bright", "lamp")),
            addEmojiItem("🔦", EmojiCategory.OBJECTS, listOf("flashlight", "light", "beam", "device")),
            addEmojiItem("🕯️", EmojiCategory.OBJECTS, listOf("candle", "light", "fire", "wax")),
            addEmojiItem("🪔", EmojiCategory.OBJECTS, listOf("diya lamp", "light", "fire", "festival")),
            addEmojiItem("🧯", EmojiCategory.OBJECTS, listOf("fire extinguisher", "safety", "tool", "fire")),
            addEmojiItem("🛢️", EmojiCategory.OBJECTS, listOf("barrel", "oil", "storage", "container")),
            addEmojiItem("💸", EmojiCategory.OBJECTS, listOf("money with wings", "cash", "spend", "finance")),
            addEmojiItem("💵", EmojiCategory.OBJECTS, listOf("dollar bills", "money", "cash", "finance")),
            addEmojiItem("💴", EmojiCategory.OBJECTS, listOf("yen bills", "money", "cash", "finance")),
            addEmojiItem("💶", EmojiCategory.OBJECTS, listOf("euro bills", "money", "cash", "finance")),
            addEmojiItem("💷", EmojiCategory.OBJECTS, listOf("pound bills", "money", "cash", "finance")),
            addEmojiItem("🪙", EmojiCategory.OBJECTS, listOf("coin", "money", "currency", "finance")),
            addEmojiItem("💰", EmojiCategory.OBJECTS, listOf("money bag", "cash", "finance", "wealth")),
            addEmojiItem("💳", EmojiCategory.OBJECTS, listOf("credit card", "money", "payment", "finance")),
            addEmojiItem("💎", EmojiCategory.OBJECTS, listOf("gem stone", "jewel", "wealth", "shiny")),
            addEmojiItem("⚖️", EmojiCategory.OBJECTS, listOf("balance scale", "justice", "law", "fairness")),
            addEmojiItem("🪜", EmojiCategory.OBJECTS, listOf("ladder", "climb", "tool", "step")),
            addEmojiItem("🧰", EmojiCategory.OBJECTS, listOf("toolbox", "tools", "repair", "work")),
            addEmojiItem("🔧", EmojiCategory.OBJECTS, listOf("wrench", "tool", "repair", "fix")),
            addEmojiItem("🔨", EmojiCategory.OBJECTS, listOf("hammer", "tool", "repair", "construction")),
            addEmojiItem("⚒️", EmojiCategory.OBJECTS, listOf("hammer and pick", "tool", "work", "mining")),
            addEmojiItem("🛠️", EmojiCategory.OBJECTS, listOf("hammer and wrench", "tool", "repair", "construction")),
            addEmojiItem("⛏️", EmojiCategory.OBJECTS, listOf("pickaxe", "tool", "mining", "dig")),
            addEmojiItem("🔩", EmojiCategory.OBJECTS, listOf("nut and bolt", "tool", "mechanic", "construction")),
            addEmojiItem("⚙️", EmojiCategory.OBJECTS, listOf("gear", "machine", "mechanism", "settings")),
            addEmojiItem("🪤", EmojiCategory.OBJECTS, listOf("mouse trap", "trap", "tool", "catch")),
            addEmojiItem("🧱", EmojiCategory.OBJECTS, listOf("brick", "construction", "material", "build")),
            addEmojiItem("⛓️", EmojiCategory.OBJECTS, listOf("chains", "tool", "link", "security")),
            addEmojiItem("🧲", EmojiCategory.OBJECTS, listOf("magnet", "tool", "science", "physics")),
            addEmojiItem("🔫", EmojiCategory.OBJECTS, listOf("gun", "weapon", "shoot", "danger")),
            addEmojiItem("💣", EmojiCategory.OBJECTS, listOf("bomb", "explosion", "weapon", "danger")),
            addEmojiItem("🧨", EmojiCategory.OBJECTS, listOf("firecracker", "explosion", "celebration", "danger")),
            addEmojiItem("🪓", EmojiCategory.OBJECTS, listOf("axe", "tool", "wood", "chop")),
            addEmojiItem("🔪", EmojiCategory.OBJECTS, listOf("knife", "tool", "cut", "weapon")),
            addEmojiItem("🗡️", EmojiCategory.OBJECTS, listOf("dagger", "weapon", "tool", "fight")),
            addEmojiItem("⚔️", EmojiCategory.OBJECTS, listOf("crossed swords", "weapon", "battle", "fight")),
            addEmojiItem("🛡️", EmojiCategory.OBJECTS, listOf("shield", "protection", "defense", "armor")),
            addEmojiItem("🚬", EmojiCategory.OBJECTS, listOf("cigarette", "smoke", "tobacco", "health")),
            addEmojiItem("⚰️", EmojiCategory.OBJECTS, listOf("coffin", "death", "burial", "rest")),
            addEmojiItem("❤️", EmojiCategory.OBJECTS, listOf("red heart", "love", "like", "romance")),
            addEmojiItem("🧡", EmojiCategory.OBJECTS, listOf("orange heart", "love", "like", "romance")),
            addEmojiItem("💛", EmojiCategory.OBJECTS, listOf("yellow heart", "love", "friendship", "like")),
            addEmojiItem("💚", EmojiCategory.OBJECTS, listOf("green heart", "love", "friendship", "nature")),
            addEmojiItem("💙", EmojiCategory.OBJECTS, listOf("blue heart", "love", "like", "trust")),
            addEmojiItem("💜", EmojiCategory.OBJECTS, listOf("purple heart", "love", "like", "royalty")),
            addEmojiItem("🖤", EmojiCategory.OBJECTS, listOf("black heart", "love", "dark", "mourning")),
            addEmojiItem("🤍", EmojiCategory.OBJECTS, listOf("white heart", "love", "peace", "pure")),
            addEmojiItem("🤎", EmojiCategory.OBJECTS, listOf("brown heart", "love", "nature", "warmth")),
            addEmojiItem("💔", EmojiCategory.OBJECTS, listOf("broken heart", "sad", "heartbreak", "love")),
            addEmojiItem("❣️", EmojiCategory.OBJECTS, listOf("heart exclamation", "love", "like", "romance")),
            addEmojiItem("💕", EmojiCategory.OBJECTS, listOf("two hearts", "love", "like", "romance")),
            addEmojiItem("💞", EmojiCategory.OBJECTS, listOf("revolving hearts", "love", "like", "romance")),
            addEmojiItem("💓", EmojiCategory.OBJECTS, listOf("beating heart", "love", "like", "romance")),
            addEmojiItem("💗", EmojiCategory.OBJECTS, listOf("growing heart", "love", "like", "romance")),
            addEmojiItem("💖", EmojiCategory.OBJECTS, listOf("sparkling heart", "love", "like", "romance")),

            );

        fun getAllEmojis() {
            TODO("Not yet implemented")
        }
    }
    private fun addEmojiItems(emojis: List<String>, category: EmojiCategory, tags: List<String>) {
        emojis.forEach { emoji ->
            allEmojis.add(EmojiItem(emoji, category, tags))
        }
    }
}